-----
# 시험을 위해 외워두면 좋을 것들
## 예상되는 것 적어봤음
-----

다시봐야 할 것들
#### 8. 문자열 메소드와 포멧팅
#### 10. 리스트의 활용
---------

In [20]:
print(bool(10+10j and 1.5))

True


In [25]:
print(divmod(5,2)) # 목과 나머지 한 번에
print(pow(2,3)) # 뭐의 몇 제곱할 때

(2, 1)
8


In [26]:
import math
print(math.pi)
print(math.e)
print(math.sqrt(2))

3.141592653589793
2.718281828459045
1.4142135623730951


In [28]:
#Indexing
s = "Dennis Cho"
print(s[0])
print(s[1])
print(s[-1])
print(s[-2])

D
e
o
h


In [34]:
#Slicing
s = "I'm winner"
print(s[1:3])
print(s[0:5])
print(s[0:])
print(s[:3])
print(s[0::2])
print(s[::-1])

s[0] = 'h' #String의 원소는 변경 불가능하다.

'm
I'm w
I'm winner
I'm
Imwne
renniw m'I


TypeError: 'str' object does not support item assignment

In [3]:
print(all([True, True, False]))
print(all([1, 2, 3]))
print(all([]))

False
True
True


In [35]:
c = [1,2,3]
d = [1,2,3]
print(c is d)
print(c == d)

False
True


In [36]:
print(bool(0)) # 정수 0은 거짓 []
print(bool(1))
print(bool(100))
print(bool(-100))
print()
print(bool(0.0)) # 실수 0.0은 거짓
print(bool(0.1))
print(bool(0.00000000000000000000000000000000000000000001))

False
True
True
True

False
True
True


In [37]:
print(bool('abc'))
print(bool('')) # 빈 문자열은 거짓 
print()
print(bool([])) # 공 리스트는 거짓
print(bool([1,2,3]))
print()
print(bool(())) # 공 튜플은 거짓
print(bool((1,2,3)))
print()
print(bool({})) # 공 사전은 거짓
print(bool({1:2}))
print()
print(bool(None)) # None 객체는 거짓

True
False

False
True

False
True

False
True

False


In [38]:
print(1 and 2)
print(1 and 0)
print()

print(0 or 2)
print(1 or 0)
print()

print([] or 1)  # [] 거짓
print([] or ()) # [], () 거짓
print([] and 1) # [] 거짓이므로 1은 참조할 필요 없음

2
0

2
1

1
()
[]


In [39]:
print([[]] or 1) # [[]] 참으로 간주
print([{}] or 1) # [{}] 참으로 간주
print('' or 1)   # 빈 문자열('')은 거짓

[[]]
[{}]
1


In [5]:
print(not(True))
print(not(1 and 2))
print(not('' or 1))

False
False
False


In [8]:
s = 'spam and egg'
s = s[:4] + ', cheese, ' + s[5:]
print(s)
# 문자열은 이와 같이 변경해야함

spam, cheese, and egg


In [9]:
print('1234'.isdigit()) # 문자열 내의 Character들이 모두 숫자인가?
print('abcd'.isalpha()) # 문자열 내의 Character들이 모두 영문자인가?
print('1abc234'.isalnum()) # 문자열 내의 Character들이 모두 영문자 또는 숫자인가? 
print('abc'.islower()) # 문자열 내의 Character들이 모두 소문자인가?
print('ABC'.isupper()) # 문자열 내의 Character들이 모두 대문자인가?
print('\t\r\n'.isspace()) # 문자열 내의 Character들이 모두 공백 문자인가?
print('This Is A Title'.istitle()) # 문자열이 Title 형식 (각 단어의 첫글자가 대문자)인가?

True
True
True
True
True
True
True


------
 리스트 내포 List Comprehension
_______

In [2]:
L = [ k * k for k in range(10)]

In [3]:
print(L)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


In [4]:
L = [[[c*w*h for w in range(1,6)] for h in range(1,5)] for c in range(1,4)]

In [6]:
import numpy
print(numpy.array(L))

[[[ 1  2  3  4  5]
  [ 2  4  6  8 10]
  [ 3  6  9 12 15]
  [ 4  8 12 16 20]]

 [[ 2  4  6  8 10]
  [ 4  8 12 16 20]
  [ 6 12 18 24 30]
  [ 8 16 24 32 40]]

 [[ 3  6  9 12 15]
  [ 6 12 18 24 30]
  [ 9 18 27 36 45]
  [12 24 36 48 60]]]


--------------

--------------
Packing and Unpacking
____________

In [8]:
t = 1, 2, 3
print(t)
print(type(t))

(1, 2, 3)
<class 'tuple'>


In [9]:
x, y, z = t
print(x, y, z)
print(type(x), type(y), type(z))

1 2 3
<class 'int'> <class 'int'> <class 'int'>


* 리스트로도 비슷한 작업이 가능하지만, 단순 패킹/언패킹 작업만을 목적으로 한다면 튜플 사용 추천

In [11]:
a = ['foo', 'bar', 4, 5]
[x, y, z, w] = a
print(x)
print(y)
print(z)
print(w)
print()

x, y, z, w = a
print(x)
print(y)
print(z)
print(w)

foo
bar
4
5

foo
bar
4
5


* E-learning에서 언급하지 않았던 집합 만드는 방법 --> 꼭 기억하세요~

In [15]:
e = {1, 2, 3, 4, 5}
print(type(e))
print(e)

<class 'set'>
{1, 2, 3, 4, 5}


In [16]:
print(set())                         # 빈 set 객체 생성
print(set([1, 2, 3, 4, 5]))         # 초기 값은 일반적으로 시퀀스 자료형인 리스트를 넣어준다.
print(set([1, 2, 3, 2, 3, 4]))      # 중복된 원소는 한 나만 저장됨
print(set('abc'))                  # 문자열은 각 문자를 집합 원소로 지닌다.  
print(set([(1, 2, 3), (4, 5, 6)]))  # 각 튜플은 원소로 가질 수 있음 
print(set([[1, 2, 3], [4, 5, 6]]))  # 변경 가능 자료인 리스트는 집합의 원소가 될 수 없다.

set()
{1, 2, 3, 4, 5}
{1, 2, 3, 4}
{'a', 'b', 'c'}
{(1, 2, 3), (4, 5, 6)}


TypeError: unhashable type: 'list'

In [1]:
print(set([{1:"aaa"}, {2:"bbb"}]))  # 변경 가능 자료인 사전도 집합의 원소가 될 수 없다.

TypeError: unhashable type: 'dict'

In [2]:
D = {'c':1, 'a':2, 'b':3}
#items = D.items()
items = list(D.items())
print(items)
print()

items.sort()
print(items)
print()

for k, v in items:
    print(k, v)

[('c', 1), ('a', 2), ('b', 3)]

[('a', 2), ('b', 3), ('c', 1)]

a 2
b 3
c 1


* 위 리스트에서 각 튜플 원소의 두번째 값을 기준으로 정렬을 해보시오 (각자 실습)

In [8]:
def test(x) :
    return x[1]
items = list(D.items())
items.sort(key = test)
print(items)

items = list(D.items())
items.sort(key = lambda a : a[1])
print(items)

[('c', 1), ('a', 2), ('b', 3)]
[('c', 1), ('a', 2), ('b', 3)]


-------
이게 될까? 싶은 것들
-------

In [10]:
def test(L):
    s = [100,200]
    L[1:3] = s
    print(L)

L = [1,2,3,4,5]

In [11]:
test(L)
print(L)

[1, 100, 200, 4, 5]
[1, 100, 200, 4, 5]


In [14]:
dic = {'a':1, 'b':2, 'c':3}
print(*dic)
print(**dic)

a b c


TypeError: 'a' is an invalid keyword argument for print()

In [5]:
list((lambda x : x**2)(20))

TypeError: 'int' object is not iterable